#!/bin/bash
# Returns the date of the next payday (last Friday of the month)
# Examples:
# payday (no arguments) -- gives this month's payday
# payday June 2020 -- gives payday in June 2020

usage () {
  echo "$0 [month year]"
  exit 1
}

report () {
  if [ $# -eq 3 ]; then
     echo -n ${2} ${3}
  else
     echo -n "This month"
  fi
  if [ $1 -eq 31 ]; then
    echo "'s payday is on the 31st."
  else
    echo "'s payday is on the ${1}th."
  fi
}

if [ $# -ne 0 -a $# -ne 2 ]; then
  usage
fi

report $(cal $1 $2 | awk '{print $6}' | grep "[0-9]" | tail -1) $1 $2
